### ISSUE TITLE
Fix posts.html

### ISSUE THREAD

**Issue by sputh** [Northern-Moose/newsaggregator#11]
when you are rendering the directive on the html page, you must convert from camel case to snake case.

ex. in .js file: 'mainDirective'
      in .html file: <main-directive></main-directive>
if you don't angular will break

**Comment by sputh** [comment]
also, please do a merge request so I can review your code. thanks a ton, buddy!

**Comment by etripier** [comment]
Pushed fix to feature/postdirective
