### ISSUE TITLE
Need to find an efficient way to time fetch calls to the API

### ISSUE THREAD

**Issue by ghost** [Northern-Moose/newsaggregator#2]
We need to decide on how we want to fetch and standardize data from multiple APIs and insert into a single collection table ('aggregated content') without duplicating data.

-cron Jobs
-garbage collection @ every API call

**Comment by seanchen1991** [comment]
Adrian advised us to use a persistent node.js server process to fetch API calls, so we'll go with that option instead of using a cron job.
